before_script:
    - git submodule update --init
    - cpanm --installdeps --notest .
    - perl Makefile.PL
    - make

run_test_suite:
    tags:
        - perl
    stage: test
    script:
        - make test
