#!/usr/bin/env perl

use FindBin '$Bin';
use lib "$Bin/regex-engine/lib";
use REE;
use Mojolicious::Lite;

# regex form (template only)
any '/' => 'home';

# information about a match
post '/match' => sub {
    my $c = shift;

    # form data
    my $regex   = $c->param('regex');
    my $input   = $c->param('input');

    # try to compile
    my $ree     = eval {REE->new(regex => $regex)};
    return $c->render(text => $@) if $@;

    # done
    $c->stash(
        regex   => $regex,
        input   => $input,
        success => $ree->match($input) ? 1 : 0,
        ree     => $ree,
    );
};

app->start;

__END__
